let message = {
  zh: {
    title: 'MacleTranlator转换日志',
    overView: '转换概览',
    compileTitle: '编译信息',
    statistics: '统计项',
    result: '结果',
    detail: '转换详情',
    col1: '组件名',
    col2: '不支持',
    col3: '如何解决',

    transformFileNum: '转换文件总数',
    transformCompletely: '完全转换',
    transformPartially: '部分转换',
    noSupport: '不支持',

    templete: '模板文件',
    jsonModular: 'json文件',
    otherModular: '其他文件',
    jsModular: '脚本文件',
    wxssModular: '样式文件',
    modularWxs: '自定义脚本',
    unsupported: '不支持文件',
    supportPart: '部分支持',
    filepath: '文件路径',
    transformResult: '转换结果',
    apiLifecycle: 'api/生命周期',
    unsupport: '不支持的部分(参数/返回值)',

    propname: '属性名称',
    support: '支持程度',
    unsupportedSubproperty: '不支持子属性',
    helpdoc: '帮助文档',
    try: '暂不支持，请尝试其他实现方式',
    fullSupport: '完整支持',

    projectName: '项目名称',
    porjectPath:'项目路径',
    outputPath:'输出路径',
    fileNum:'文件数'
  },
  en: {
    title: 'MacleTranlator transform log',
    overView: 'Transform Overview',
    compileTitle: 'Project Information',
    statistics: 'Statistical Items',
    result: 'Result',
    detail: 'Transform Detail',
    col1: 'Component Name',
    col2: 'notSupport',
    col3: 'How to Fix',

    transformFileNum: 'Total number of files',
    transformCompletely: 'Completely Converted',
    transformPartially: 'Partially Converted',
    noSupport: 'Not Supported',

    templete: 'Template',
    jsonModular: 'Json',
    otherModular: 'Other',
    jsModular: 'JS',
    wxssModular: 'Style File',
    modularWxs: 'WXS',
    unsupported: 'Unsupported',
    supportPart: 'Supported Partly',
    filepath: 'File Path',
    transformResult: 'Transform Result',
    apiLifecycle: 'Api/Lifecycle',
    unsupport: 'Unsupported(params/returnValues)',
    propname: 'Prop Name',
    support: 'Support',
    unsupportedSubproperty: 'Unsupported Subproperty',
    helpdoc: 'Help Doc',
    try: 'Temporary does not support, please try other ways',
    fullSupport: 'fullSupport',

    projectName:'Project Name',
    porjectPath:'Project Path',
    outputPath:'Output Path',
    fileNum:'Number of File'
  }
};